export enum MainActionTypes {
  CLOSE_SIDEBAR = 'CLOSE_SIDEBAR',
  OPEN_SIDEBAR = 'OPEN_SIDEBAR',
  RESET_ALERT = 'RESET_ALERT',
  SHOW_ALERT = 'SHOW_ALERT',
  GET_USER_INFO = 'GET_USER_INFO',
  EDIT_REQUEST_PROPERTY = 'EDIT_REQUEST_PROPERTY',
  CLEAR_REQUEST_PROPERTY = 'CLEAR_REQUEST_PROPERTY',
}
